import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { swaggerUI } from '@hono/swagger-ui';
import { OpenAPIHono } from '@hono/zod-openapi';
import { logger } from './middlewares/logger';
import { config } from './config/config';
import contactsRoutes from './contacts/contacts.routes';

const app = new Hono();
const apiV1 = new OpenAPIHono();

// CORS middleware
app.use('*', cors({
  origin: config.cors.origins,
  allowHeaders: ['Content-Type', 'Authorization'],
  allowMethods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS'],
  maxAge: 600,
  credentials: true,
}));

// Logger middleware
app.use('*', logger());

// The OpenAPI documentation will be auto-generated by @hono/zod-openapi
apiV1.doc('/openapi.json', {
  openapi: '3.0.0',
  info: {
    title: 'Contacts & Prospects API',
    version: '1.0.0',
    description: 'API REST para gestionar contactos, clientes y prospectos.',
  },
  servers: [
    {
      url: `${config.productionUrl}/api/v1`,
      description: 'Production server',
    },
    {
      url: `http://localhost:${config.port}/api/v1`,
      description: 'Development server',
    },
  ],
});

apiV1.get('/doc', swaggerUI({ url: '/api/v1/openapi.json' }));

// Feature routes
apiV1.route('/', contactsRoutes);

app.route('/api/v1', apiV1);

// 404 handler
app.notFound((c) => {
  return c.json({ 
    success: false,
    error: 'Not Found', 
    path: c.req.path 
  }, 404);
});

// Error handler
app.onError((err, c) => {
  console.error('Unhandled error:', err);
  const msg = err.message ?? '';

  // JSON estricto (RFC 8259): sin coma después del último campo; Swagger a veces envía `{"a":1,}`.
  if (
    err instanceof SyntaxError ||
    /Malformed JSON|Unexpected token|JSON Parse error/i.test(msg)
  ) {
    return c.json(
      {
        success: false,
        error: 'Bad Request',
        message:
          'JSON del body inválido. Suele deberse a una coma final tras el último campo; quítala. Ejemplo válido: {"id_tag":3}',
      },
      400
    );
  }

  return c.json({
    success: false,
    error: 'Internal Server Error',
    message: msg,
  }, 500);
});

export default app;
